### ISSUE TITLE
bluetooth scanner with disconnected event will crash the app

### ISSUE THREAD

**Issue by futurist** [michael-may/cordova-zebra-scanner#2]
I've added bluetooth scanner code as below:

in `BarcodeScanner.java`:

```java
if(device.getConnectionType() == DCSSDKDefs.DCSSDK_CONN_TYPES.DCSSDK_CONNTYPE_USB_SNAPI
   || device.getConnectionType() == DCSSDKDefs.DCSSDK_CONN_TYPES.DCSSDK_CONNTYPE_BT_NORMAL
) {
  Log.d("ScannerListEvent", "--------FOUND USB SCANNER--------");
  ... ...

... ...
private String getSnapiBarcode() {
  BarCodeView barCodeView = sdkHandler.dcssdkGetPairingBarcode(
                DCSSDKDefs.DCSSDK_BT_PROTOCOL.LEGACY_B,
                DCSSDKDefs.DCSSDK_BT_SCANNER_CONFIG.KEEP_CURRENT
        );
  ... ...
```

And in `NotificationReceiver.java`

```java
BarcodeScanner.sdkHandler.dcssdkEnableAvailableScannersDetection(true);
BarcodeScanner.sdkHandler.dcssdkSetOperationalMode(DCSSDKDefs.DCSSDK_MODE.DCSSDK_OPMODE_BT_NORMAL);
... ...
```

It worked when tested with a DS6878-SR scanner, but the app will crash when the scanner out of bluetooth bounds, or just close the bluetooth signal, which will emit a `broadcastScannerDisconnected` event, but after the event invoked, the app crashed.

I don't know what's the problem, could you help with the bluetooth connection feature?

PS: I'm also use the offical `barcode_scanner_library_v2.1.4.0.aar` file instead of the `jar` lib, since it can auto check and open bluetooth of the Android when launched.

**Comment by michael-may** [comment]
Sorry, I can't be much help here.

I've only tested USB functionality and, unfortunately, I don't have the necessary hardware to be able to debug this for bluetooth.

Let me know if you solve it, I'd definitely consider pull requests for that feature.
